### PR TITLE
Fix segfault for compiling copygb with this version of iplib

### PR DESCRIPTION
**Pull request by mkavulich**
Fixing a segault for copygb.exe when using this version of NCEPlibs

This was accomplished by compiling iplib with 4-byte reals; the original code has an inconsistency when selecting -DLSIZE=d rather than -DLSIZE=8; which promotes some variables but not others for some reason. UPP and copygb use 4-byte reals regardless, so this has been changed to -DLSIZE=4.

Additionally, this commit renames the file src/ip/v3.0.0/sorc/gdswzd_c.F90 to src/ip/v3.0.0/sorc/gdswzd_c.F to avoid case-insensitivity problem on MacOS. This is the only file which needs pre-processing due to this real size thing, not sure why it's so limited but there ya go.

### CODE REVIEW

**Comment by mkavulich** [comment]
I haven't yet tested this for UPP to make sure it doesn't break that, but it really shouldn't. I'll test it tomorrow.

**Comment by hertneky** [comment]
On linux system puffling using the gnu compiler, it does not appear to be making the gdswzd_c.o and so making the libip library failes.

**Comment by mkavulich** [comment]
@hertneky Sorry about that, I forgot to commit the makefile change necessary for the fix to work; it should be working now.

**Comment by hertneky** [comment]
@mkavulich 
- successful build of this branch on Linux (puffling) - commit 4ccdb1....
- successful build and run of UPP within uffda (both grib1/grib2, gnu) using this NCEPlibs build
- successful build and execution of copygb.exe using this NCEPlibs build

**Comment by mkavulich** [comment]
Tests on UFFDA, Hera, and Puffling have all passed for both UPP and copygb. Good to merge.

**Pull request merged**
